# Assignment of 0530_ 정찬연
### 0-9칼럼 = 사람별 점수 set
### 10 칼럼 = 정답
### 0-19 행 = 객관식
### 21-22행 = 주관식
1. 마지막 칼럼을 answer에 대입
2. 나머지를 score
3. score 중에서 정답 True, 오답 False
* 정답을 -> answer
* 객관식 답안 -> dset
* dset중 정답 = True, 오답 = False
4. 각 사람의 객관심 점수 4점 (true의 개수 센 후 x4, 점수계산)
5. numpy dot 연산 이용해 사람별 점수 계산

In [27]:
import numpy as np

In [28]:
score = np.loadtxt('python_score.csv', delimiter=',', dtype = 'float64')

In [29]:
score

array([[ 3.,  3.,  4.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  3.,  4.,  4.,  2.,  2.,  4.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.],
       [ 2.,  2.,  3.,  2.,  4.,  2.,  2.,  4.,  4.,  2.,  2.],
       [ 2.,  4.,  2.,  4.,  2.,  2.,  2.,  2.,  4.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  2.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  3.,  4.,  4.,  2.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  2.,  3.,  3.,  3.,  3.,  1.,  3.,  3.,  3.,  3.],
       [ 2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  1.,  1.,  2.,  2

In [30]:
answer = score[:20,-1]
# 각 문제의 정답 

In [31]:
answer

array([3., 4., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2., 1.,
       2., 2., 2.])

In [32]:
dset = score[:20,:10].T
#객관식 답안 도출

In [33]:
dset

array([[3., 4., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 2.],
       [3., 4., 1., 1., 2., 4., 1., 4., 4., 2., 3., 3., 3., 2., 2., 2.,
        1., 2., 2., 1.],
       [4., 4., 1., 1., 3., 2., 1., 4., 4., 2., 4., 3., 3., 3., 4., 2.,
        1., 2., 4., 2.],
       [3., 4., 1., 1., 2., 4., 1., 4., 4., 2., 4., 2., 3., 3., 2., 1.,
        1., 2., 2., 4.],
       [3., 4., 1., 1., 4., 2., 1., 4., 4., 2., 2., 3., 3., 3., 2., 1.,
        1., 2., 2., 4.],
       [3., 3., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 2.],
       [3., 4., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 1., 2., 2.,
        1., 2., 2., 3.],
       [3., 4., 1., 1., 4., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 2.],
       [3., 2., 1., 2., 4., 4., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        2., 4., 2., 1.],
       [3., 2., 1., 1., 2., 2., 1., 4., 2., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 3.]])

In [34]:
bool_dset = (dset == answer)
# 정답과 비교하여 True, False 나누기

In [35]:
bool_dset

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True, False,  True,  True,  True,  True,
         True, False],
       [False,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True, False,  True,  True,
         True, False],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True,
         True, False],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ T

In [36]:
dset[dset!=answer]=0
dset[dset!=0]=1
dset
# 정답과 답안이 맞지 않을경우 숫자 0 으로 변환 (이유는 답안지에 이미 1이 있어 겹치는 부분이 있어 답변에 없는 숫자를 사용)
# 그후 0을 다시 1로 변환 

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1.,
        1., 1., 1., 0.],
       [0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
        1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0.,
        1., 1., 1., 0.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0.,
        1., 1., 1., 0.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
        1., 1., 1., 0.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        0., 0., 1., 0.],
       [1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 0.]])

In [37]:
score

array([[ 1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  3.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  4.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  2.],
       [ 1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  2.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  4.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  4.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.],
       [ 1.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  4.],
       [ 1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  3.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  3.],
       [ 1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  3.],
       [ 1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.],
       [ 1.,  1.,  1.,  0.,  0.,  1.,  1

In [38]:
lst = [4]*20

In [39]:
s = lst + [1,1]
s

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1]

In [44]:
a = score[:,:-1].T
a
#스코어 값을 transpose해줌으로 인하여 스코어 행 열 변환

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  9.,  5.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,
         0.,  1.,  1.,  1.,  1.,  1.,  0.,  4.,  7.],
       [ 0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  0.,  1.,  1.,  1.,  0.,  1., 10.,  8.],
       [ 1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,
         1.,  1.,  0.,  1.,  1.,  1.,  0.,  9.,  5.],
       [ 1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,
         1.,  1.,  0.,  1.,  1.,  1.,  0.,  6.,  7.],
       [ 1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  8.,  8.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         0.,  1.,  1.,  1.,  1.,  1.,  0., 10.,  6.],
       [ 1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1., 

In [46]:
x =np.dot(a,s)
#dot을 통하여 맞은 객관식과 주관식 점수를 합산한 총점 도출 

In [48]:
x

array([94., 75., 82., 78., 77., 92., 88., 91., 67., 87.])

In [50]:
for i,v in enumerate(x,1):
    print (i,':',v)
#보기쉬운 포멧 변경

1 : 94.0
2 : 75.0
3 : 82.0
4 : 78.0
5 : 77.0
6 : 92.0
7 : 88.0
8 : 91.0
9 : 67.0
10 : 87.0
