# Assignment of 0531_ 정찬연
### 4장에 있는 표 4-3 ~ 표 4-8까지의 내용을 읽고 관련자료를 조사하여 정리 후 발표

In [3]:
import numpy as np

### 표 4-5 기본 배열 통계 메서드

메서드 | 설명
---------| --------
sum | 배열전체 혹은 특정 축에 대한 모든 원소의 합을 계산 (크기가 0인 배열에 대한 sum = 0)
mean | 산술 평균을 구한다 (크기가 0인 배열에 대한 mean = NaN
std, var | 표준편차(std), 분산(var)을 구한다. 
min,max | 최소값, 최대값
argmin, argmax | 최소 원소의 색인 값, 최대 원소의 색인 값
cumsum | 각 원소의 누적 합
cumprod | 각 원소의 누적 곱

In [4]:
np.sum([0.5, 1.5])

2.0

In [5]:
np.sum([[0, 1], [0, 5]])

6

In [7]:
arr = np.random.randn(8)
arr

array([-1.45683453, -0.54071026, -0.88322215,  0.01570073, -0.59893456,
       -0.98821458,  0.72523586,  0.67331948])

In [8]:
arr.mean()

-0.38170750179297275

In [9]:
arr.std()

0.7368916312338422

In [10]:
arr.var()

0.5430092761824727

In [11]:
arr.min()

-1.4568345313790267

In [12]:
arr.max()

0.725235855846658

In [30]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
np.argmin(arr1)

0

In [32]:
np.argmax(arr1)

8

In [35]:
arr1.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [36]:
arr1.cumprod(0)

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]], dtype=int32)

### 표 4-6 배열 집합 연산

메서드 | 설명
---------| --------
unique(x) | 배열 x에서 중복된 원소를 제거, 정렬 후  반환
intersect1d(x,y) | 배열 x 와 y에 공통적으로 존재하는 원소 정렬 후 반환
union1d(x,y) | 두 배열의 합집합 반환
in1d(x,y) | x의 원소중 y의 원소를 포함하는지 나타내는 불리열 배열 반환
setdiff1d(x,y) | x와 y의 차집합을 반환
setxor1d(x,y)| 한배열에는 포함되지만 두 배열 모두에 포함되지 않는 원소들의 집합인 대칭차집합을 반환

In [38]:
arr2 = np.array([[1, 1], [2, 3]])
np.unique(arr2)

array([1, 2, 3])

In [41]:
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 3])

In [42]:
np.union1d([-1, 0, 1], [-2, 0, 2])

array([-2, -1,  0,  1,  2])

In [46]:
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
np.setdiff1d(a, b)

array([1, 2])

In [44]:
a = np.array([1, 2, 3, 2, 4])
b = np.array([2, 3, 5, 7, 5])
np.setxor1d(a,b)

array([1, 4, 5, 7])

### 표 4-7 자주 사용하는 nympy.linalg 함수

메서드 | 설명
---------| --------
numpy.diag | 정사각 행렬의 대각/비대각 원소를 1차원 배열로 반환 또는 1차원 배열을 대각선 원소로 하고 나머지 0으로 채운 단위행렬 반환
numpy.dot | 행렬 곱셈
numpy.trace | 행렬의 대각선 원소의 합을 계산
numpy.linalg.det | 행렬식을 계산
numpy.linalg.eig | 정사각 행렬의 고유값과 고유벡터를 계산
numpy.linalg.inv | 정사각 행렬의 역행렬을 계산
numpy.linalg.pinv | 행렬의 무어-펜로즈 유사역원 역행렬을 구함
numpy.linalg.qr | QR 분해를 계산
numpy.linalg.svd | 특이값 분해(SVD)를 계산
numpy.linalg.solve | A가 정사각 행렬일때, Ax = b를 만족하는 x를 구한다
numpy.linalg.lstsq | y = xb 를 만족하는 최소제곱해를 구한다.

In [47]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
np.diag(x)

array([0, 4, 8])

In [51]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [53]:
np.trace(a)

2

In [54]:
np.trace(b)

6

In [60]:
np.linalg.det(a)

1.0

In [56]:
np.linalg.det(b)

6.0

* 1x1 행렬의 행렬식
    * det([a]) = a
* 2x2 행렬의 행렬식
    * det([a b
           c d]) = ad - bc
* 3x3 행렬의 행렬식
    * det([a b c
           d e f
           g h i]) = aei + bfg + cdh - ceg - bdi - afh

In [61]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [62]:
np.linalg.det(a) # 1x4 - 2x3 = -2

-2.0000000000000004

In [68]:
x = np.array([[2,2,0], [-2,1,1],[3,0,1]])
np.linalg.eig(x)

(array([0.82780538+2.10555033j, 0.82780538-2.10555033j,
        2.34438924+0.        j]),
 array([[ 0.03855929-0.4714928 j,  0.03855929+0.4714928 j,
          0.40793471+0.        j],
        [ 0.47377641+0.31693492j,  0.47377641-0.31693492j,
          0.07024416+0.        j],
        [-0.6717856 +0.        j, -0.6717856 -0.        j,
          0.91030491+0.        j]]))

* 고유치와 고유벡터를 모두 반환을 해준다

In [64]:
x = np.array([[2,2,0], [-2,1,1],[3,0,1]])
np.linalg.inv(x)
#역행렬을 구한 것 

array([[ 0.08333333, -0.16666667,  0.16666667],
       [ 0.41666667,  0.16666667, -0.16666667],
       [-0.25      ,  0.5       ,  0.5       ]])

### 무어펜로즈 역행렬
* 무어-펜로즈 의사 역행렬은 역행렬이 존재하지 않는 경우 부분적으로 역행렬과 유사한 역할을 할 수 있는 행렬입니다. 이 행렬은 시스템에 유일한 해가 없거나 해가 많을 때 선형 방정식 시스템의 해를 구하는 데 자주 사용됩니다.

### QR 분해
* qr 분해는 어떤 행렬을 직교행렬과 윗삼각행렬의 곱으로 표현하는 것

In [69]:
x = np.array([[2,2,0], [-2,1,1],[3,0,1]])
x

array([[ 2,  2,  0],
       [-2,  1,  1],
       [ 3,  0,  1]])

In [70]:
q,r = np.linalg.qr(x)

In [66]:
q

array([[-0.48507125, -0.80845208, -0.33333333],
       [ 0.48507125, -0.56591646,  0.66666667],
       [-0.72760688,  0.16169042,  0.66666667]])

In [67]:
r

array([[-4.12310563, -0.48507125, -0.24253563],
       [ 0.        , -2.18282063, -0.40422604],
       [ 0.        ,  0.        ,  1.33333333]])